"""add credit check constraints and auto timestamp updates

Revision ID: aaca6b7a8f6e
Revises: a12f09931d5d
Create Date: 2026-09-27 10:53:11.693402

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "aaca6b7a8f6e"
down_revision: Union[str, Sequence[str], None] = "a12f09931d5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "UPDATE evaluation_runs SET job_id = 'legacy_job_' || id WHERE job_id IS NULL"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evaluation_runs", "job_id", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evaluation_runs", "job_id", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
